### ISSUE TITLE
Got render error on custom form

### ISSUE THREAD

**Issue by semiherdogan** [venits/native-forms#4]
I've tried with example form, it works fine.
But when i try with my custom form (i have custom css and javascript) , i got render error. 
You can check image below. 
Any suggestion about how can i fix this error?

![image](https://user-images.githubusercontent.com/5646041/160632465-858cf15b-17dc-4ab6-bc7c-87efe8a0cb90.png)

**Comment by tomekvenits** [comment]
Hi, does your form contain "Image" question block? 
It's my first guess that something might be wrong with it.

**Comment by semiherdogan** [comment]
Yes, i removed that question block (which includes image) and its working, thanks
